CREATE TABLE LANGUAGE
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     NAME        VARCHAR(50) NOT NULL UNIQUE,
     CODE        VARCHAR(10) NOT NULL UNIQUE,
     CONSTRAINT LANGUAGE_PK PRIMARY KEY(ID)
  );


CREATE TABLE PROFILE
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     LOGIN       VARCHAR(50) UNIQUE NOT NULL,
     PASSWORD    VARCHAR(50) NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT PROFILE_PK PRIMARY KEY(ID),
     CONSTRAINT PROFILE_LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE (ID)
  );

CREATE TABLE ROLE
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     NAME       VARCHAR(50) UNIQUE NOT NULL,
     CONSTRAINT ROLE_PK PRIMARY KEY(ID)
  );


CREATE TABLE PROFILE_ROLE
  (
     PROFILE_ID NUMBER(10) NOT NULL,
     ROLE_ID NUMBER(10) NOT NULL,
     CONSTRAINT PROFILE_FK FOREIGN KEY(PROFILE_ID) REFERENCES PROFILE(ID),
     CONSTRAINT ROLE_FK FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
  );

CREATE TABLE SUBJECT
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     NAME        VARCHAR(50) UNIQUE NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT SUBJECT_PK PRIMARY KEY(ID),
     CONSTRAINT LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(ID)
  );

CREATE TABLE EXAM
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1),
     NAME       VARCHAR(50) UNIQUE NOT NULL,
     SUBJECT_ID NUMBER(10) NOT NULL,
     CONSTRAINT EXAM_PK PRIMARY KEY(ID),
     CONSTRAINT SUBJECT_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(ID)
  );

CREATE TABLE QUESTION
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     TEXT VARCHAR(500) NOT NULL,
     EXAM_ID       NUMBER(10) NOT NULL,
     CONSTRAINT QUESTION_PK PRIMARY KEY(ID),
     CONSTRAINT EXAM_FK FOREIGN KEY(EXAM_ID) REFERENCES EXAM(ID)
  );

CREATE TABLE ANSWER
  (
     ID NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1) NOT NULL,
     TEXT VARCHAR(500) NOT NULL,
     QUESTION_ID NUMBER(10) NOT NULL,
     IS_CORRECT    NUMBER(1) NOT NULL,
     CONSTRAINT QUESTION_FK FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID),
     CONSTRAINT ANSWER_PK PRIMARY KEY(ID)
  );
