-- USER SQL
CREATE USER EXAMINATION_PORTAL IDENTIFIED BY admin 
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK ;

-- ROLES
GRANT "DBA" TO EXAMINATION_PORTAL WITH ADMIN OPTION;
GRANT "CONNECT" TO EXAMINATION_PORTAL WITH ADMIN OPTION;
ALTER USER EXAMINATION_PORTAL DEFAULT ROLE "DBA","CONNECT";
