CREATE TABLE EXAMINATION_PORTAL.LANGUAGE
  (
     ID NUMBER(10) NOT NULL,
     NAME        VARCHAR(50) NOT NULL UNIQUE,
     CODE        VARCHAR(10) NOT NULL UNIQUE,
     CONSTRAINT LANGUAGE_PK PRIMARY KEY(ID)
  );

CREATE SEQUENCE EXAMINATION_PORTAL.LANGUAGE_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.LANGUAGE_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.LANGUAGE
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.LANGUAGE_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.PROFILE
  (
     ID  NUMBER(10) NOT NULL,
     LOGIN       VARCHAR(50) UNIQUE NOT NULL,
     PASSWORD    VARCHAR(50) NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT PROFILE_PK PRIMARY KEY(ID),
     CONSTRAINT PROFILE_LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE (ID)
  );

CREATE SEQUENCE EXAMINATION_PORTAL.PROFILE_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.PROFILE_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.PROFILE
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.PROFILE_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.ROLE
  (
     ID  NUMBER(10) NOT NULL,
     NAME       VARCHAR(50) UNIQUE NOT NULL,
     CONSTRAINT ROLE_PK PRIMARY KEY(ID)
  );

CREATE SEQUENCE EXAMINATION_PORTAL.ROLE_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.ROLE_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.ROLE
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.ROLE_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.PROFILE_ROLE
    (
        PROFILE_ID NUMBER(10) NOT NULL,
        ROLE_ID NUMBER(10) NOT NULL,
        CONSTRAINT PROFILE_FK FOREIGN KEY(PROFILE_ID) REFERENCES PROFILE(ID),
        CONSTRAINT ROLE_FK FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
    );


CREATE TABLE EXAMINATION_PORTAL.SUBJECT
  (
     ID  NUMBER(10) NOT NULL,
     NAME        VARCHAR(50) UNIQUE NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT SUBJECT_PK PRIMARY KEY(ID),
     CONSTRAINT LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(ID)
  );
  
CREATE SEQUENCE EXAMINATION_PORTAL.SUBJECT_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.SUBJECT_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.SUBJECT
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.SUBJECT_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.EXAM
  (
     ID    NUMBER(10),
     NAME       VARCHAR(50) UNIQUE NOT NULL,
     SUBJECT_ID NUMBER(10) NOT NULL,
     CONSTRAINT EXAM_PK PRIMARY KEY(ID),
     CONSTRAINT SUBJECT_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(ID)
  );

CREATE SEQUENCE EXAMINATION_PORTAL.EXAM_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.EXAM_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.EXAM
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.EXAM_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.QUESTION
  (
     ID   NUMBER(10) NOT NULL,
     TEXT VARCHAR(500) NOT NULL,
     EXAM_ID       NUMBER(10) NOT NULL,
     CONSTRAINT QUESTION_PK PRIMARY KEY(ID),
     CONSTRAINT EXAM_FK FOREIGN KEY(EXAM_ID) REFERENCES EXAM(ID)
  );
  
CREATE SEQUENCE EXAMINATION_PORTAL.QUESTION_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.QUESTION_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.QUESTION
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.QUESTION_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/


CREATE TABLE EXAMINATION_PORTAL.ANSWER
  (
     ID   NUMBER(10) NOT NULL,
     TEXT VARCHAR(500) NOT NULL,
     QUESTION_ID NUMBER(10) NOT NULL,
     IS_CORRECT    NUMBER(1) NOT NULL,
     CONSTRAINT QUESTION_FK FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID),
     CONSTRAINT ANSWER_PK PRIMARY KEY(ID)
  );

CREATE SEQUENCE EXAMINATION_PORTAL.ANSWER_SEQ;

CREATE OR REPLACE TRIGGER EXAMINATION_PORTAL.ANSWER_AUTOINCREMENT
  BEFORE INSERT ON EXAMINATION_PORTAL.ANSWER
  FOR EACH ROW
BEGIN
    SELECT EXAMINATION_PORTAL.ANSWER_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;
END;
/