DROP TABLE EXAMINATION_PORTAL.ANSWER;
DROP SEQUENCE EXAMINATION_PORTAL.ANSWER_SEQ;

DROP TABLE EXAMINATION_PORTAL.QUESTION;
DROP SEQUENCE EXAMINATION_PORTAL.QUESTION_SEQ;

DROP TABLE EXAMINATION_PORTAL.EXAM;
DROP SEQUENCE EXAMINATION_PORTAL.EXAM_SEQ;

DROP TABLE EXAMINATION_PORTAL.SUBJECT;
DROP SEQUENCE EXAMINATION_PORTAL.SUBJECT_SEQ;

DROP TABLE EXAMINATION_PORTAL.PROFILE_ROLE;

DROP TABLE EXAMINATION_PORTAL.PROFILE;
DROP SEQUENCE EXAMINATION_PORTAL.PROFILE_SEQ;

DROP TABLE EXAMINATION_PORTAL.ROLE;
DROP SEQUENCE EXAMINATION_PORTAL.ROLE_SEQ;

DROP TABLE EXAMINATION_PORTAL.LANGUAGE;
DROP SEQUENCE EXAMINATION_PORTAL.LANGUAGE_SEQ;
