DROP TABLE TESTING_PORTAL.TUTOR;
DROP SEQUENCE TESTING_PORTAL.TUTOR_SEQ;

CREATE TABLE TESTING_PORTAL.TUTOR
  (
     TUTOR_ID NUMBER(10) NOT NULL,
     LOGIN    VARCHAR(50) NOT NULL UNIQUE,
     PASSWORD VARCHAR(50) NOT NULL,
     CONSTRAINT TUTOR_PK PRIMARY KEY(TUTOR_ID)
  );

CREATE SEQUENCE TESTING_PORTAL.TUTOR_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.TUTOR_AUTO_INCREMENT
  BEFORE INSERT ON TESTING_PORTAL.TUTOR
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.TUTOR_SEQ.NEXTVAL
    INTO   :NEW.TUTOR_ID
    FROM   DUAL;
END;
/



DROP TABLE TESTING_PORTAL.LANGUAGE;
DROP SEQUENCE TESTING_PORTAL.LANGUAGE_SEQ;

CREATE TABLE TESTING_PORTAL.LANGUAGE
  (
     LANGUAGE_ID NUMBER(10) NOT NULL,
     NAME        VARCHAR(50) NOT NULL UNIQUE,
     CODE        VARCHAR(10) NOT NULL UNIQUE,
     CONSTRAINT LANGUAGE_PK PRIMARY KEY(LANGUAGE_ID)
  );

CREATE SEQUENCE TESTING_PORTAL.LANGUAGE_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.LANGUAGE_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.LANGUAGE
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.LANGUAGE_SEQ.NEXTVAL
    INTO   :NEW.LANGUAGE_ID
    FROM   DUAL;
END;
/



DROP TABLE TESTING_PORTAL.SUBJECT;
DROP SEQUENCE TESTING_PORTAL.SUBJECT_SEQ;

CREATE TABLE TESTING_PORTAL.SUBJECT
  (
     SUBJECT_ID  NUMBER(10) NOT NULL,
     NAME        VARCHAR(50) UNIQUE NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT SUBJECT_PK PRIMARY KEY(SUBJECT_ID),
     CONSTRAINT LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(
     LANGUAGE_ID)
  );
  
CREATE SEQUENCE TESTING_PORTAL.SUBJECT_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.SUBJECT_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.SUBJECT
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.SUBJECT_SEQ.NEXTVAL
    INTO   :NEW.SUBJECT_ID
    FROM   DUAL;
END;
/


DROP TABLE TESTING_PORTAL.STUDENT;
DROP SEQUENCE TESTING_PORTAL.STUDENT_SEQ;

CREATE TABLE TESTING_PORTAL.STUDENT
  (
     STUDENT_ID  NUMBER(10) NOT NULL,
     LOGIN       VARCHAR(50) UNIQUE NOT NULL,
     PASSWORD    VARCHAR(50) NOT NULL,
     LANGUAGE_ID NUMBER(10) NOT NULL,
     CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID),
     CONSTRAINT STUDENT_LANGUAGE_FK FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE
     (LANGUAGE_ID)
  );

CREATE SEQUENCE TESTING_PORTAL.STUDENT_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.STUDENT_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.STUDENT
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.STUDENT_SEQ.NEXTVAL
    INTO   :NEW.STUDENT_ID
    FROM   DUAL;
END;
/



DROP TABLE TESTING_PORTAL.TEST;
DROP SEQUENCE TESTING_PORTAL.TEST_SEQ;

CREATE TABLE TESTING_PORTAL.TEST
  (
     TEST_ID    NUMBER(10),
     NAME       VARCHAR(50) NOT NULL,
     SUBJECT_ID NUMBER(10) NOT NULL,
     TUTOR_ID   NUMBER(10) NOT NULL,
     CONSTRAINT TEST_PK PRIMARY KEY(TEST_ID),
     CONSTRAINT SUBJECT_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID
     ),
     CONSTRAINT TUTOR_FK FOREIGN KEY(TUTOR_ID) REFERENCES TUTOR(TUTOR_ID)
  );

CREATE SEQUENCE TESTING_PORTAL.TEST_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.TEST_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.TEST
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.TEST_SEQ.NEXTVAL
    INTO   :NEW.TEST_ID
    FROM   DUAL;
END;
/


DROP TABLE TESTING_PORTAL.QUESTION;
DROP SEQUENCE TESTING_PORTAL.QUESTION_SEQ;

CREATE TABLE TESTING_PORTAL.QUESTION
  (
     QUESTION_ID   NUMBER(10) NOT NULL,
     QUESTION_TEXT VARCHAR(500) NOT NULL,
     TEST_ID       NUMBER(10) NOT NULL,
     CONSTRAINT QUESTION_PK PRIMARY KEY(QUESTION_ID),
     CONSTRAINT TEST_FK FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID)
  );
  
CREATE SEQUENCE TESTING_PORTAL.QUESTION_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.QUESTION_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.QUESTION
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.QUESTION_SEQ.NEXTVAL
    INTO   :NEW.QUESTION_ID
    FROM   DUAL;
END;
/


DROP TABLE TESTING_PORTAL.ANSWER;
DROP SEQUENCE TESTING_PORTAL.ANSWER_SEQ;

CREATE TABLE TESTING_PORTAL.ANSWER
  (
     ANSWER_ID   NUMBER(10) NOT NULL,
     ANSWER_TEXT VARCHAR(500) NOT NULL,
     QUESTION_ID NUMBER(10) NOT NULL,
     IS_RIGHT    NUMBER(1) NOT NULL,
     CONSTRAINT QUESTION_FK FOREIGN KEY(QUESTION_ID) REFERENCES TESTING_PORTAL.QUESTION(
     QUESTION_ID),
     CONSTRAINT ANSWER_PK PRIMARY KEY(ANSWER_ID)
  );

CREATE SEQUENCE TESTING_PORTAL.ANSWER_SEQ;

CREATE OR REPLACE TRIGGER TESTING_PORTAL.ANSWER_AUTOINCREMENT
  BEFORE INSERT ON TESTING_PORTAL.ANSWER
  FOR EACH ROW
BEGIN
    SELECT TESTING_PORTAL.ANSWER_SEQ.NEXTVAL
    INTO   :NEW.ANSWER_ID
    FROM   DUAL;
END;
/