INSERT INTO PROFILE (LOGIN, PASSWORD, LANGUAGE_ID) 
VALUES('Peter','Peter',(SELECT ID FROM LANGUAGE WHERE NAME LIKE 'English'));

INSERT INTO PROFILE (LOGIN, PASSWORD, LANGUAGE_ID) 
VALUES('Joe','Joe',(SELECT ID FROM LANGUAGE WHERE NAME LIKE 'English'));

INSERT INTO PROFILE (LOGIN, PASSWORD, LANGUAGE_ID) 
VALUES('Abraham','Abraham',(SELECT ID FROM LANGUAGE WHERE NAME LIKE 'English'));

INSERT INTO ROLE (NAME) VALUES('student');
INSERT INTO ROLE (NAME) VALUES('tutor');

INSERT INTO PROFILE_ROLE (PROFILE_ID, ROLE_ID)
VALUES((SELECT ID FROM PROFILE WHERE PROFILE.LOGIN  LIKE 'Peter'),(SELECT ID FROM ROLE WHERE ROLE.NAME LIKE 'tutor'));
INSERT INTO PROFILE_ROLE (PROFILE_ID, ROLE_ID)
VALUES((SELECT ID FROM PROFILE WHERE PROFILE.LOGIN  LIKE 'Peter'),(SELECT ID FROM ROLE WHERE ROLE.NAME LIKE 'student'));

INSERT INTO PROFILE_ROLE (PROFILE_ID, ROLE_ID)
VALUES((SELECT ID FROM PROFILE WHERE PROFILE.LOGIN LIKE 'Joe'),(SELECT ID FROM ROLE WHERE ROLE.NAME LIKE 'student'));

INSERT INTO PROFILE_ROLE (PROFILE_ID, ROLE_ID)
VALUES((SELECT ID FROM PROFILE WHERE PROFILE.LOGIN LIKE 'Abraham'),(SELECT ID FROM ROLE WHERE ROLE.NAME LIKE 'tutor'));