INSERT INTO TESTING_PORTAL.LANGUAGE
(NAME, CODE)
VALUES('English', 'en');

INSERT INTO TESTING_PORTAL.SUBJECT
  (NAME, LANGUAGE_ID)
VALUES('Math', 
  (SELECT language_id FROM TESTING_PORTAL.LANGUAGE WHERE CODE = 'en')
);


INSERT INTO TESTING_PORTAL.TUTOR
  (LOGIN, PASSWORD)
VALUES('admin', 'admin');

INSERT INTO TESTING_PORTAL.TEST 
  (NAME, SUBJECT_ID, TUTOR_ID)
VALUES ('Basic math',
  (SELECT subject_id FROM TESTING_PORTAL.SUBJECT WHERE NAME = 'Math'),
  (SELECT tutor_id FROM TESTING_PORTAL.TUTOR WHERE LOGIN = 'admin')
);

INSERT INTO TESTING_PORTAL.QUESTION
  (QUESTION_TEXT, TEST_ID)
VALUES ('2 + 2',
  (SELECT test_id FROM TESTING_PORTAL.TEST WHERE NAME = 'Basic math')
);

INSERT INTO TESTING_PORTAL.QUESTION
  (QUESTION_TEXT, TEST_ID)
VALUES ( '1 + 0',
  (SELECT test_id FROM TESTING_PORTAL.TEST WHERE NAME = 'Basic math')
);


INSERT INTO TESTING_PORTAL.QUESTION
  (QUESTION_TEXT, TEST_ID)
VALUES ('5 * 2',
  (SELECT test_id FROM TESTING_PORTAL.TEST WHERE NAME = 'Basic math')
);

INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('1',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '2 + 2'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('2',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '2 + 2'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('3',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '2 + 2'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('4',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '2 + 2'), '1');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('5',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '2 + 2'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('0',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '1 + 0'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('1',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '1 + 0'), '1');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('11', (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '1 + 0'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('10', (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '5 * 2'), '1');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('5',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '5 * 2'), '0');
INSERT INTO TESTING_PORTAL.ANSWER (ANSWER_TEXT, QUESTION_ID, IS_RIGHT) VALUES ('2',  (SELECT QUESTION_ID FROM TESTING_PORTAL.QUESTION WHERE QUESTION_TEXT = '5 * 2'), '0');
