DROP TABLE TESTING_PORTAL.TUTOR;
DROP SEQUENCE TESTING_PORTAL.TUTOR_SEQ;

DROP TABLE TESTING_PORTAL.ANSWER;
DROP SEQUENCE TESTING_PORTAL.ANSWER_SEQ;

DROP TABLE TESTING_PORTAL.QUESTION;
DROP SEQUENCE TESTING_PORTAL.QUESTION_SEQ;

DROP TABLE TESTING_PORTAL.TEST;
DROP SEQUENCE TESTING_PORTAL.TEST_SEQ;

DROP TABLE TESTING_PORTAL.STUDENT;
DROP SEQUENCE TESTING_PORTAL.STUDENT_SEQ;

DROP TABLE TESTING_PORTAL.SUBJECT;
DROP SEQUENCE TESTING_PORTAL.SUBJECT_SEQ;

DROP TABLE TESTING_PORTAL.LANGUAGE;
DROP SEQUENCE TESTING_PORTAL.LANGUAGE_SEQ;
